#!/bin/sh
arg=$1

echo "STARTING PROJECT $PROJECT_NAME!";

if [ ! -d "./node_modules" ] || [ "$arg" = "--no-cache" ]
then
  echo "INSTALLING DEPENDENCIES...";

  npm install
  npx prisma generate

  echo "DEPENDENCIES INSTALLED SUCCESSFULLY...";
fi

if [ "$DATABASE_URL" = "" ]; then
    echo "DATABASE_URL is not set yet!"
else
    echo "DATABASE_URL is set!"
    echo "NOT RUN MIGRATE IN DATABASE MONGO!"
fi

echo "RUNNING BUILD PROJECT...";

npm run build

echo "PROJECT WAS BUILD SUCCESSFULLY!";

echo "RUNNING APPLICATION SERVER!";

node ./dist/src/server.js

echo "APPLICATION DONE!";